### ISSUE TITLE
*(c::Number, A::Operator)

### ISSUE THREAD

**Issue by MikaelSlevinsky** [JuliaApproximation/ApproxFunBase.jl#11]
This function, at https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/master/src/Operators/general/algebra.jl#L574, doesn't quite work with dual numbers, particularly because `dual(0,1) == 0` and `dual(1,1) == 1`, which do not behave like other field extensions, e.g. complex.

```julia
julia> dual(0,1)*Evaluation(S, 1)
ZeroOperator : Chebyshev() → ConstantSpace(Point(1))
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ⋯

julia> dual(eps(),1)*Evaluation(S, 1)
ConstantTimesOperator : Chebyshev() → ConstantSpace(Point(1))
 2.220446049250313e-16 + 1.0ɛ  …  2.220446049250313e-16 + 1.0ɛ  ⋯

julia> dual(1,1)*Evaluation(S, 1)
ConcreteEvaluation : Chebyshev() → ConstantSpace(Point(1))
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  ⋯

julia> dual(1+eps(),1)*Evaluation(S, 1)
ConstantTimesOperator : Chebyshev() → ConstantSpace(Point(1))
 1.0000000000000002 + 1.0ɛ  …  1.0000000000000002 + 1.0ɛ  ⋯

```

**Comment by dlfivefifty** [comment]
Probably. hanging it to `c === zero(c)` and `c === one(c)` fixes it?

**Comment by MikaelSlevinsky** [comment]
That would fail for `BigFloat` because they're mutable but not treated as such.

Is there a good reason for the cases? Seems there are three different type outcomes of this method. Does `ConstantTimesOperator` have a big overhead compared with `ZeroOperator`?

**Comment by dlfivefifty** [comment]
Poor design? Premature  optimisation? Feel free to delete it and see if tests still pass

**Comment by MikaelSlevinsky** [comment]
The very next line is suspect too: any reason why `*(A::Operator,c::Number) = A*(c*one(domainspace(A)))` isn't `*(A::Operator,c::Number) = c*A`?

**Comment by dlfivefifty** [comment]
Because it’s applying the operator to a constant function, which returns a function. If/when it’s revamped, operators will be functions of functions, applying an operator will be ` A(f) ` instead of ` A*f ` and composing operators will be ` A\circ B ` instead of ` A*B `. 

This will in practice be lowered to quasi arrays which have well-defined matrix operations
