### ISSUE TITLE
Why is `Fun` mutable?

### ISSUE THREAD

**Issue by jishnub** [JuliaApproximation/ApproxFunBase.jl#135]
Are there instances where one needs to modify the fields of a `Fun`, as opposed to the coefficients?

**Comment by jishnub** [comment]
Related: #136, where I check if changing this breaks anything

**Comment by dlfivefifty** [comment]
I can't remember. The only thing I can think of is if there was a space where the coefficients were stored in a `Matrix` in which case `resize!` is not possible.... but if tests pass I'm sure it's fine.
