### ISSUE TITLE
Seem like the Bug in the code ApproxFunBase/src/Caching/almostbanded.jl line106

### ISSUE THREAD

**Issue by Jiaqi-knight** [JuliaApproximation/ApproxFunBase.jl#5]
Debug the error code, I found that 
almostbanded.jl line81     --->ds=domainspace(io)
almostbanded.jl line106   ---->bl = blocklengths(ds[k])
where, k is the integer, however, In the below case, ds=domainspace(A),is like Laurent(0.1🕒+1.0 + 0.0im)⨄Laurent(0.1🕒+-0.4999999999999998 + 0.8660254037844387im)⨄Laurent(0.1🕒+-0.5000000000000004 - 0.8660254037844385im)
which means ds[1] is no meaning!!!

~~~>
This headache me for many days, when I try to complete the example code in SingularIntergralEquation Package.
I tested my code here:
using ApproxFun, SingularIntegralEquations,Plots,ApproxFunBase
g1(x,y) = 0.5
N=3
r=0.1
cr = exp.(im*2π*(0:N-1)/N)
crl,crr = (1-2im*r)cr,(1+2im*r)cr
@show dom=Circle(cr[1],r) ∪ Circle(cr[2],r)∪ Circle(cr[3],r)
#@show dom = ∪(Segment.(crl[1:end],crr[1:end])...)

@show sp = Space(dom)
cwsp = CauchyWeight(sp⊗sp,0)
⨍ = DefiniteLineIntegral(dom)
@time G = GreensFun(g1,cwsp;method=:Cholesky)
A=⨍[G]
ApproxFun.qr(A) #error occurs

Here A is union InterlaceOperator such like that: Laurent(0.1🕒+1.0 + 0.0im)⨄Laurent(0.1🕒+-0.4999999999999998 + 0.8660254037844387im)⨄Laurent(0.1🕒+-0.5000000000000004 - 0.8660254037844385im) → Laurent(0.1🕒+1.0 + 0.0im)⨄Laurent(0.1🕒+-0.4999999999999998 + 0.8660254037844387im)⨄Laurent(0.1🕒+-0.5000000000000004 - 0.8660254037844385im)

**Comment by mjp98** [comment]
I think this can be fixed by replacing calls to `getindex(sp::DirectSumSpace,k)`, such as `ds[k]`,  with `component(sp,k)` in Caching/almostbanded.jl.

I would be happy to put a pull request together for this.

**Comment by jishnub** [comment]
A PR is welcome

**Comment by jishnub** [comment]
Fixed by https://github.com/JuliaApproximation/ApproxFunBase.jl/pull/121
