### ISSUE TITLE
Predicting number of coefficients in output of operator

### ISSUE THREAD

**Issue by Luapulu** [JuliaApproximation/ApproxFunBase.jl#80]
I want to apply some operators like derivatives to `Fun`s and would like to know how many coefficients and points I'll get out. I found that

https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/25ee448cbde61ef8e01f5c9d5af63ac3364a751c/src/Operators/Operator.jl#L401-L404

seems to be where the number of output coefficients is decided. I tried to look into the `colstop` function but I can't seem to figure out what it does. The one that gets called in my case is:

https://github.com/JuliaApproximation/ApproxFunBase.jl/blob/25ee448cbde61ef8e01f5c9d5af63ac3364a751c/src/PDE/KroneckerOperator.jl#L77-L83

Could you explain what the two functions shown above do and why? Specifically, I want to understand how to predict what number of output coefficients derivatives on a Chebyshev^2 basis will produce and what number of coefficients I will get when converting from Chebyshev to Ultraspherical basis.

Here's a MWE

```Julia
using FastTransforms: paduapoints
using ApproxFunOrthogonalPolynomials

np = 1000
ppoints = paduapoints(ceil(Int, (-3 + sqrt(1 + 8 * np)) / 2))

f(v) = cos(v[1]) * sin(v[2])
vals = f.(eachrow(ppoints))

CC = Chebyshev(-1..1)         ⊗ Chebyshev(-1..1)
UC = Ultraspherical(1, -1..1) ⊗ Chebyshev(-1..1)
CU = Chebyshev(-1..1)         ⊗ Ultraspherical(1, -1..1)
UU = Ultraspherical(1, -1..1) ⊗ Ultraspherical(1, -1..1)

CCtoUU = Conversion(CC, UU)

D1 = Derivative(CC, [1,0])
UCtoUU = Conversion(UC, UU)

coeffs = transform(CC, vals)
pf = Fun(CC, coeffs)

ncoefficients(pf)  # 1035
ncoefficients(D1 * pf)  # 990: why?
ncoefficients(UCtoUU * (D1 * pf))  # also 990
ncoefficients(CCtoUU * pf)  # 1035
```

**Comment by dlfivefifty** [comment]
`colstop(A, i)` gives the last non-zero entry the `i`-th column of a matrix/operator `A`.

**Comment by Luapulu** [comment]
Ahh, thanks! that helps.

**Comment by Luapulu** [comment]
I'll close for now, since I think I understand now how ApproxFun get the number of output coefficients. Thanks again.
